desc 'Update qualities'

namespace :db do
  namespace :seed do
    task :insert_qualities => :environment do
      ActiveRecord::Base.transaction do
        [ 
          { label: 'Organisation' , value: 'organisation' },
          { label: 'Planung' , value: 'planung' },
          { label: 'Produktion' , value: 'produktion' },
          { label: 'Montage' , value: 'montage' },
          { label: 'Service' , value: 'service' },
          { label: 'Reparatur' , value: 'reparatur' },
          { label: 'Vetrieb' , value: 'vertrieb' },
          { label: 'Verkauf' , value: 'verkauf' },
          { label: 'Einkauf' , value: 'einkauf' },
          { label: 'Abbrechnung' , value: 'abrechnung' },
          { label: 'Personla' , value: 'personla' },
          { label: 'Beratung' , value: 'beratung' },
          { label: 'Kreation' , value: 'kreation' },
          { label: 'Sanierung' , value: 'sanierung' },
          { label: 'Wartung' , value: 'wartung' },
          { label: 'Arbeitsvorbereitung' , value: 'arbeitsvorbereitung' },
          { label: 'Entwicklung' , value: 'entwicklung' },
          { label: 'Marketing' , value: 'marketing' },
          { label: 'Verhandlung' , value: 'verhandlung' },
          { label: 'Ausführung' , value: 'ausfuhrung' },
          { label: 'Führen' , value: 'fuhren' },
          { label: 'Überwachung' , value: 'uberwachung' },
          { label: 'Leitung' , value: 'leitung' },
          { label: 'Analyse' , value: 'analyse' },
          { label: 'Mathe' , value: 'mathe' },
          { label: 'Deutsch' , value: 'deutsch' },
          { label: 'Englisch' , value: 'englisch' },
          { label: 'Sprachen' , value: 'sprachen' },
          { label: 'Physik' , value: 'physik' },
          { label: 'Biologie' , value: 'biologie' },
          { label: 'Chemie' , value: 'chemie' },
          { label: 'Informatik' , value: 'informatik' },
          { label: 'Programmierung' , value: 'programmierung' },
          { label: 'Webdesign' , value: 'webdesign' },
          { label: 'Software' , value: 'software' },
          { label: 'Sozial' , value: 'sozial' },
          { label: 'Umgang mit Menschen' , value: 'umgang_mit_menschen' },
          { label: 'Networking' , value: 'networking' },
          { label: 'Service Gastro' , value: 'service_gastro' },
          { label: 'Umgang mit Lebensmitteln' , value: 'umgang_mit_lebensmitteln' }
        ].each do |skill|
          Skill.create!(label: skill[:label], value: skill[:value])
        end

        [ 
          { label: 'Handwerk' , value: 'handwerk' },
          { label: 'Industrie' , value: 'industrie' },
          { label: 'Elektro' , value: 'elektro' },
          { label: 'Metallverarbeitung' , value: 'metallverarbeitung' },
          { label: 'Holzverarbeitung' , value: 'holzverarbeitung' },
          { label: 'Baubranche' , value: 'baubranche' },
          { label: 'Maschinen' , value: 'maschinen' },
          { label: 'Projektentwicklung' , value: 'projektentwicklung' },
          { label: 'Technik' , value: 'technik' },
          { label: 'Energie' , value: 'energie' },
          { label: 'Straßenbau' , value: 'straßenbau' },
          { label: 'Mechanik' , value: 'mechanik' },
          { label: 'Automobil' , value: 'automobil' },
          { label: 'Zweirad' , value: 'zweirad' },
          { label: 'Sanitär/Heizung' , value: 'sanitar_heizung' },
          { label: 'erneuerbare Energie' , value: 'erneuerbare_energie' },
          { label: 'Anlagenbau' , value: 'anlagenbau' },
          { label: 'Maler/Lackierer' , value: 'maler_lackierer' },
          { label: 'Chemie' , value: 'chemie' },
          { label: 'Konstruktion' , value: 'konstruktion' },
          { label: 'Logistik' , value: 'logistik' },
          { label: 'Maschinenbau' , value: 'maschinenbau' },
          { label: 'kaufmännische Bereiche' , value: 'kaufmannische_bereiche' },
          { label: 'Immobilien' , value: 'immobilien' },
          { label: 'Hotel' , value: 'hotel' },
          { label: 'Gastronomie' , value: 'gastronomie' },
          { label: 'Bar' , value: 'bar' },
          { label: 'Club' , value: 'club' },
          { label: 'Restaurant' , value: 'restaurant' },
          { label: 'Imbiss' , value: 'imbiss' },
          { label: 'Catering' , value: 'catering' },
          { label: 'Events' , value: 'events' },
          { label: 'Lebensmittelverarbeitung' , value: 'lebensmittelverarbeitung' },
          { label: 'Design' , value: 'design' },
          { label: 'Reinigung' , value: 'reinigung' },
          { label: 'Pflege' , value: 'Pflege' },
          { label: 'Menschen' , value: 'menschen' },
          { label: 'Digitalisierung' , value: 'digitalisierung' },
          { label: 'Entwicklung' , value: 'entwicklung' },
          { label: 'Trends' , value: 'trends' },
          { label: 'Mobilität' , value: 'mobilitat' },
          { label: 'Medien' , value: 'medien' },
          { label: 'Sicherheit' , value: 'sicherheit' },
          { label: 'Verwaltung' , value: 'verwaltung' },
          { label: 'Buchhaltung' , value: 'buchhaltung' },
          { label: 'Politik' , value: 'politik' },
          { label: 'Finanzen' , value: 'finanzen' },
          { label: 'Steuern' , value: 'steuern' },
          { label: 'Versicherung' , value: 'versicherung' },
          { label: 'Büro' , value: 'buro' },
          { label: 'Gesetze' , value: 'gesetze' },
          { label: 'Recht' , value: 'recht' },
          { label: 'Umwelt' , value: 'umwelt' },
          { label: 'Natur' , value: 'natur' },
          { label: 'Tiere' , value: 'tiere' },
          { label: 'Reisen' , value: 'reisen' },
          { label: 'Kinder' , value: 'kinder' },
          { label: 'Lehren' , value: 'lehren' },
          { label: 'Weiterbildung' , value: 'weiterbildung' },
          { label: 'Forschung' , value: 'forschung' },
          { label: 'Psychologie' , value: 'psychologie' },
          { label: 'Pädagogik' , value: 'pädagogik' },
          { label: 'Kosmetik' , value: 'kosmetik' },
          { label: 'Gesundheit' , value: 'gesundheit' },
          { label: 'Fitness' , value: 'fitness' },
          { label: 'Medizin' , value: 'medizin' },
          { label: 'Pflege' , value: 'pflege' },
          { label: 'medizinische Fachkraft' , value: 'medizinische_fachkraft' }
        ].each do |interest|
          Interest.create!(label: interest[:label], value: interest[:value])
        end

        [ 
          { label: 'kommunikativ' , value: 'kommunikativ' },
          { label: 'sympatisch' , value: 'sympatisch' },
          { label: 'emphatisch' , value: 'emphatisch' },
          { label: 'teamfähig' , value: 'teamfahig' },
          { label: 'sozial' , value: 'sozial' },
          { label: 'couragiert' , value: 'couragiert' },
          { label: 'tolerant' , value: 'tolerant' },
          { label: 'respektvoll' , value: 'respektvoll' },
          { label: 'offen' , value: 'offen' },
          { label: 'freundlich' , value: 'freundlich' },
          { label: 'flexibel' , value: 'flexibel' },
          { label: 'diszipliniert' , value: 'diszipliniert' },
          { label: 'kritikfähig' , value: 'kritikfahig' },
          { label: 'kompromissfähig' , value: 'kompromissfahig' },
          { label: 'eigenverantwortlich' , value: 'eigenverantwortlich' },
          { label: 'rational' , value: 'rational' },
          { label: 'belastbar' , value: 'belastbar' },
          { label: 'fit' , value: 'fit' },
          { label: 'selbstbewusst' , value: 'selbstbewusst' },
          { label: 'risikobereit' , value: 'risikobereit' },
          { label: 'sicherheitsbedacht' , value: 'sicherheitsbedacht' },
          { label: 'hygienisch' , value: 'hygienisch' },
          { label: 'geduldig' , value: 'geduldig' },
          { label: 'handwerklich begabt' , value: 'handwerklich_begabt' },
          { label: 'geschickt' , value: 'geschickt' },
          { label: 'kombinatorisch' , value: 'kombinatorisch' },
          { label: 'analytisch' , value: 'analytisch' },
          { label: 'strukturiert' , value: 'strukturiert' },
          { label: 'zielstrebig' , value: 'zielstrebig' },
          { label: 'ehrgeizig' , value: 'ehrgeizig' },
          { label: 'gewissenhaft' , value: 'gewissenhaft' },
          { label: 'verantwortungsbewusst' , value: 'verantwortungsbewusst' },
          { label: 'organisiert' , value: 'organisiert' },
          { label: 'pünktlich' , value: 'punktlich' },
          { label: 'loyal' , value: 'loyal' },
          { label: 'ehrlich' , value: 'ehrlich' },
          { label: 'visuell' , value: 'visuell' },
          { label: 'kreativ' , value: 'kreativ' },
          { label: 'lernbereit' , value: 'lernbereit' },
          { label: 'innovativ' , value: 'innovativ' },
          { label: 'motiviert' , value: 'motiviert' },
          { label: 'engagiert' , value: 'engagiert' },
          { label: 'wissbegierig' , value: 'wissbegierig' }
        ].each do |strenght|
          Strength.create!(label: strenght[:label], value: strenght[:value])
        end
      end
    end
  end
end