version: '2.1'
services:
  web:
    build: .
    image: next_step_api
    volumes:
      - .:/app
    ports:
      - '3003:3003'
      - '1234:1234'
      - '26162:26162'
    depends_on:
      - postgres
    environment:
      - RACK_ENV=development
      - SECRET_KEY_BASE
      - RUBY_DEBUG_PORT=1234
    tty: true
    stdin_open: true
    command: bin/bundle exec rdebug-ide --host 0.0.0.0 --port 1234 -- bin/bundle exec puma -t 5:5 -p 3003 -e development

  postgres:
    image: postgres:9.6
    ports:
      - '5432:5432'

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms1024m -Xmx1024m'
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./docker_data/elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  redis:
    image: 'redis:4.0-alpine'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - './docker_data/redis/data:/data'

  sidekiq:
    depends_on:
      - 'postgres'
      - 'redis'
    build: .
    command: bundle exec sidekiq -q default -q mailers --environment ${RACK_ENV:-development}
    volumes:
      - '.:/app'
