apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backend-rails
  labels:
    name: backend-rails
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: backend-rails
    spec:
      containers:
        - name: backend-rails
          image: gcr.io/pimenta-success/nextstep_backend_rails:develop-stable
          ports:
            - containerPort: 3003
          livenessProbe:
            httpGet:
              path: /v1/pings/
              port: 3003
            initialDelaySeconds: 20
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /v1/pings/
              port: 3003
            initialDelaySeconds: 20
            timeoutSeconds: 5
          env:
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: backend-rails-secrets
                  key: secret_key_base
            - name: RACK_ENV
              valueFrom:
                secretKeyRef:
                  name: backend-rails-secrets
                  key: rack_env
            - name: FRONTEND_HOST
              valueFrom:
                secretKeyRef:
                  name: backend-rails-secrets
                  key: frontend-host
            - name: SENDGRID_API_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-rails-secrets
                  key: sendgridapikey
