---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name:  backend-rails-secrets
data:
  secret_key_base: cGFzc3dvcmQ=
  rack_env: cHJvZHVjdGlvbg==
  sendgridapikey: U0cuYW9DQTdzS1BUd3ViN3FLY0dkci1tQS44cVRKeXRtaUdWcC04ZEJ3ZlpORG9Mdi1oNXROQUhZM28wa1JoN3d1U08w
  frontend-host: YXBwLmMyc3UuZGU=
  postgres_password: cGFzc3dvcmQ=
