development:
  cloud_name: gouvermxt
  api_key: '654732999378492'
  api_secret: cFLg7i_OTDThAe4V1R66V9gMeQY
  enhance_image_tag: true
  static_image_support: false
  secure: true
production:
  cloud_name: gouvermxt
  api_key: '654732999378492'
  api_secret: cFLg7i_OTDThAe4V1R66V9gMeQY
  enhance_image_tag: true
  static_image_support: true
  secure: true
test:
  cloud_name: gouvermxt
  api_key: '654732999378492'
  api_secret: cFLg7i_OTDThAe4V1R66V9gMeQY
  enhance_image_tag: true
  static_image_support: false
