# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18baceffbbdde90e815baee3e730a70216ec82a6d2f38ceb0915848a604d585abb09178527c9efa743aac234738349a099ce6650fc8a08e18a80712cd43c9aca

test:
  secret_key_base: 1d906046272fafa4fb62480eb81565b2b7cc997af5eb52386424f5330743a58e665b40b55584786f95c599198219e242404c3172a7b26e76c42b96e58fcebe12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
